apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-cm
  name: nginx-deploy-cm
  namespace: testbed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy-cm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy-cm
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: cm-for-html
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
      volumes:
      - name: cm-for-html
        configMap:
          name: nginx-index-cm 
status: {}
